services:
  load-balancer:
    build: ./load-balancer
    container_name: load-balancer
    volumes:
      - ./load-balancer/config.yml:/app/config.yml
    ports:
      - "8000:80"
    networks:
      - app-network
    env_file:
      - ./load-balancer/.env

  backends:
    build: ./backend-api
    ports:
      - "5000"
    networks:
      - app-network
    deploy:
      replicas: 3
    env_file:
      - ./backend-api/.env

networks:
  app-network:
    driver: bridge