listeners:
  - path_prefix: "/weighted"
    path_rewrite: "/v1"
    target_group: "backend-weighted"

target_groups:
  - name: "backend-weighted"
    targets:
      - hostname: "192.168.0.12"
        port: 5001
        weight: 3
        healthcheck:
          path: "/health"
          status_code: 
            - 200
          timeout: 2
      - hostname: "192.168.0.12"
        port: 5002
        weight: 2
        healthcheck:
          path: "/health"
          status_code:
            - 200
          timeout: 2
      - hostname: "192.168.0.12"
        port: 5003
        weight: 1
        healthcheck:
          path: "/health"
          status_code:
            - 200
          timeout: 2